#!/usr/bin/env python3
"""
One-time script to create empty stub source and header files for each .s file
generated by splat, mirroring the asm path into src/ and include/.

  Develop/  →  .cpp / .hpp  (C++ game code)
  usr/      →  .c   / .h    (C PS2 SDK library code)

Skips:
  - Files under asm/data/ (data sections, not code)
  - Files that already exist (safe to re-run)
"""

import sys
from pathlib import Path

script_dir = Path(__file__).parent
root_dir = script_dir.parent

ASM_DIR = root_dir / "build" / "SLUS-21642-PROTO-070901" / "asm"
SRC_DIR = root_dir / "src"
INCLUDE_DIR = root_dir / "include"

# Only generate stubs for these top-level subdirs of asm/
ALLOWED_ROOTS = {"Develop", "usr"}


def main() -> None:
    created_cpp = 0
    created_h = 0
    skipped = 0

    for asm_file in sorted(ASM_DIR.rglob("*.s")):
        rel = asm_file.relative_to(ASM_DIR)

        # Skip if not under an allowed root (e.g. data/)
        if rel.parts[0] not in ALLOWED_ROOTS:
            continue

        base = rel.with_suffix("")

        # Develop/ is C++ game code → .cpp/.hpp; usr/ is C SDK code → .c/.h
        is_cpp = rel.parts[0] == "Develop"
        src_ext = ".cpp" if is_cpp else ".c"
        hdr_ext = ".hpp" if is_cpp else ".h"

        cpp_path = SRC_DIR / base.with_suffix(src_ext)
        h_path = INCLUDE_DIR / base.with_suffix(hdr_ext)

        if not cpp_path.exists():
            cpp_path.parent.mkdir(parents=True, exist_ok=True)
            cpp_path.write_text("", encoding="utf-8")
            print(f"  created  {cpp_path.relative_to(root_dir)}")
            created_cpp += 1
        else:
            skipped += 1

        if not h_path.exists():
            h_path.parent.mkdir(parents=True, exist_ok=True)
            h_path.write_text("", encoding="utf-8")
            print(f"  created  {h_path.relative_to(root_dir)}")
            created_h += 1
        else:
            skipped += 1

    print(
        f"\nDone: {created_cpp} .cpp stubs, {created_h} .h stubs created, "
        f"{skipped} already existed."
    )


if __name__ == "__main__":
    sys.exit(main())
