###
# PS2 project generator adapted from decomp-toolkit template
# Generates build.ninja and objdiff.json for PS2/MWCCPS2 projects.
#
# This is specifically adapted for Sonic Riders: Zero Gravity (PS2)
# and maintains compatibility with splat-based workflows.
###

import io
import json
import os
import platform
import sys
import re
from pathlib import Path
from typing import Any, cast, Dict, Iterable, List, Optional, Set, Tuple, TypedDict, Union

from . import ninja_syntax
from .ninja_syntax import serialize_path

if sys.platform == "cygwin":
    sys.exit(
        f"Cygwin/MSYS2 is not supported."
        f"\nPlease use native Windows Python instead."
        f"\n(Current path: {sys.executable})"
    )

Library = Dict[str, Any]
PrecompiledHeader = Dict[str, Any]


class BuildConfigUnit(TypedDict):
    object: Optional[str]
    name: str
    autogenerated: bool


# Module configuration
class BuildConfigModule(TypedDict):
    name: str
    module_id: int
    ldscript: str
    entry: str
    units: List[BuildConfigUnit]


# Module link configuration
class BuildConfigLink(TypedDict):
    modules: List[str]


# Build configuration
class BuildConfig(BuildConfigModule):
    version: str
    modules: List[BuildConfigModule]
    links: List[BuildConfigLink]


class Object:
    def __init__(self, completed: bool, name: str, **options: Any) -> None:
        self.name = name
        self.completed = completed
        self.options: Dict[str, Any] = {
            "add_to_all": None,
            "asflags": None,
            "asm_dir": None,
            "cflags": None,
            "extra_asflags": [],
            "extra_cflags": [],
            "extra_clang_flags": [],
            "lib": None,
            "mw_version": None,
            "progress_category": None,
            "scratch_preset_id": None,
            "shift_jis": None,
            "source": name,
            "src_dir": None,
        }
        self.options.update(options)

        # Internal
        self.src_path: Optional[Path] = None
        self.asm_path: Optional[Path] = None
        self.src_obj_path: Optional[Path] = None
        self.asm_obj_path: Optional[Path] = None
        self.ctx_path: Optional[Path] = None

    def resolve(self, config: "ProjectConfig", lib: Library) -> "Object":
        # Use object options, then library options
        obj = Object(self.completed, self.name, **lib)
        for key, value in self.options.items():
            if value is not None or key not in obj.options:
                obj.options[key] = value

        # Use default options from config
        def set_default(key: str, value: Any) -> None:
            if obj.options[key] is None:
                obj.options[key] = value

        set_default("add_to_all", True)
        set_default("asflags", config.asflags)
        set_default("asm_dir", config.asm_dir)
        set_default("mw_version", config.linker_version)
        set_default("shift_jis", config.shift_jis)
        set_default("src_dir", config.src_dir)

        # Validate progress categories
        def check_category(category: str):
            if not any(category == c.id for c in config.progress_categories):
                sys.exit(
                    f"Progress category '{category}' missing from config.progress_categories"
                )

        progress_category = obj.options["progress_category"]
        if isinstance(progress_category, list):
            for category in progress_category:
                check_category(category)
        elif progress_category is not None:
            check_category(progress_category)

        # Resolve paths
        build_dir = config.out_path()
        obj.src_path = Path(obj.options["src_dir"]) / obj.options["source"]
        if obj.options["asm_dir"] is not None:
            obj.asm_path = (
                Path(obj.options["asm_dir"]) / obj.options["source"]
            ).with_suffix(".s")
        base_name = Path(self.name).with_suffix("")
        obj.src_obj_path = build_dir / "src" / f"{base_name}.o"
        obj.asm_obj_path = build_dir / "obj" / f"{base_name}.o"
        obj.ctx_path = build_dir / "src" / f"{base_name}.ctx"
        return obj


class ProgressCategory:
    def __init__(self, id: str, name: str) -> None:
        self.id = id
        self.name = name


class ProjectConfig:
    def __init__(self) -> None:
        # Paths
        self.build_dir: Path = Path("build")
        self.src_dir: Path = Path("src")
        self.tools_dir: Path = Path("tools")
        self.asm_dir: Optional[Path] = None

        # Tooling
        self.binutils_tag: Optional[str] = None
        self.binutils_path: Optional[Path] = None
        self.compilers_tag: Optional[str] = None
        self.compilers_path: Optional[Path] = None
        self.dtk_tag: Optional[str] = None
        self.dtk_path: Optional[Path] = None
        self.mwccps2_tag: Optional[str] = None
        self.sjiswrap_tag: Optional[str] = None
        self.sjiswrap_path: Optional[Path] = None
        self.wibo_tag: Optional[str] = None
        self.wrapper: Optional[Path] = None
        self.ninja_path: Optional[Path] = None
        self.objdiff_tag: Optional[str] = None
        self.objdiff_path: Optional[Path] = None

        # Project config
        self.non_matching: bool = False
        self.check_sha_path: Optional[Path] = None
        self.config_path: Optional[Path] = None
        self.symbol_addrs_path: Optional[Path] = None
        self.generate_map: bool = False
        self.asflags: Optional[List[str]] = None
        self.ldflags: Optional[List[str]] = None
        self.libs: Optional[List[Library]] = None
        self.precompiled_headers: Optional[List[PrecompiledHeader]] = None
        self.linker_version: Optional[str] = None
        self.version: Optional[str] = None
        self.warn_missing_config: bool = False
        self.warn_missing_source: bool = False
        self.reconfig_deps: Optional[List[Path]] = None
        self.custom_build_rules: Optional[List[Dict[str, Any]]] = (
            None  # Custom ninja build rules
        )
        self.custom_build_steps: Optional[Dict[str, List[Dict[str, Any]]]] = (
            None  # Custom build steps, types are ["pre-compile", "post-compile", "post-link", "post-build"]
        )
        self.short_loop_workaround: bool = True
        self.shift_jis = True
        self.generate_compile_commands: bool = True
        self.extra_clang_flags: List[str] = []

        # decomp.me scratch settings
        self.scratch_preset_id: Optional[int] = None
        self.scratch_platform: str = "ps2"
        # Include dirs passed to decompctx.py (e.g. ["include"])
        self.ctx_include_dirs: List[str] = ["include"]

        # Progress output
        self.progress = True
        self.progress_each_module: bool = False
        self.progress_categories: List[ProgressCategory] = []

    def validate(self) -> None:
        required_attrs = [
            "build_dir",
            "src_dir",
            "tools_dir",
            "check_sha_path",
            "config_path",
            "ldflags",
            "linker_version",
            "libs",
            "version",
        ]
        for attr in required_attrs:
            if getattr(self, attr) is None:
                sys.exit(f"ProjectConfig.{attr} missing")

    def objects(self) -> Dict[str, Object]:
        out = {}
        for lib in self.libs or {}:
            objects: List[Object] = lib["objects"]
            for obj in objects:
                if obj.name in out:
                    sys.exit(f"Duplicate object name {obj.name}")
                out[obj.name] = obj.resolve(self, lib)
        return out

    def out_path(self) -> Path:
        return self.build_dir / str(self.version)

    def compilers(self) -> Path:
        if self.compilers_path:
            return self.compilers_path
        elif self.compilers_tag:
            return self.build_dir / "compilers"
        else:
            sys.exit("ProjectConfig.compilers_tag missing")

    def compiler_wrapper(self) -> Optional[Path]:
        wrapper = self.wrapper

        if self.use_wibo():
            wrapper = self.build_dir / "tools" / "wibo"
        if not is_windows() and wrapper is None:
            wrapper = Path("wine")

        return wrapper

    def use_wibo(self) -> bool:
        return (
            self.wibo_tag is not None
            and (sys.platform == "linux" or sys.platform == "darwin")
            and platform.machine() in ("i386", "x86_64", "aarch64", "arm64")
            and self.wrapper is None
        )

    def sjiswrap(self) -> Path:
        if self.sjiswrap_path:
            return self.sjiswrap_path
        elif self.sjiswrap_tag:
            return self.build_dir / "tools" / "sjiswrap.exe"
        else:
            sys.exit("ProjectConfig.sjiswrap_tag missing")


def is_windows() -> bool:
    return os.name == "nt"


# On Windows, we need this to use && in commands
CHAIN = "cmd /c " if is_windows() else ""
# Native executable extension
EXE = ".exe" if is_windows() else ""


def file_is_asm(path: Path) -> bool:
    return path.suffix.lower() == ".s"


def file_is_c(path: Path) -> bool:
    return path.suffix.lower() == ".c"


def file_is_cpp(path: Path) -> bool:
    return path.suffix.lower() in (".cc", ".cp", ".cpp", ".cxx", ".pch++")


def file_is_c_cpp(path: Path) -> bool:
    return file_is_c(path) or file_is_cpp(path)


def make_flags_str(flags: Optional[List[str]]) -> str:
    if flags is None:
        return ""
    return " ".join(flags)


def get_pch_out_name(config: ProjectConfig, pch: PrecompiledHeader) -> str:
    pch_rel_path = Path(pch["source"])
    pch_out_name = pch_rel_path.with_suffix(".mch")
    # Keep the Ninja output absolute so MWCC-generated depfiles refer to the
    # same path as the PCH build edge.
    return os.path.abspath(config.out_path() / "include" / pch_out_name)


# Short loop workaround for MWCCPS2
COMMENT_PART = r"\/\* (.+) ([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2}) \*\/"
INSTRUCTION_PART = r"(\b(bne|bnel|beq|beql|bnez|bnezl|beqzl|bgez|bgezl|bgtz|bgtzl|blez|blezl|bltz|bltzl|b)\b.*)"
OPCODE_PATTERN = re.compile(f"{COMMENT_PART}  {INSTRUCTION_PART}")

PROBLEMATIC_FUNCS = set([
    "UpdateJtActive__FP2JTP3JOYf",
    "AddMatrix4Matrix4__FP7MATRIX4N20",
    "FInvertMatrix__FiPfT1",
    "PwarpFromOid__F3OIDT0",
    "RenderMsGlobset__FP2MSP2CMP2RO",
    "ProjectBlipgTransform__FP5BLIPGfi",
    "DrawTvBands__FP2TVR4GIFS",
    "LoadShadersFromBrx__FP18CBinaryInputStream",
    "FillShaders__Fi",
    "FUN_001aea70",
    "ApplyDzg__FP3DZGiPiPPP2SOff",
    "BounceRipgRips__FP4RIPG",
    "UpdateStepPhys__FP4STEP",
    "PredictAsegEffect__FP4ASEGffP3ALOT3iP6VECTORP7MATRIX3T6T6",
    "ExplodeExplsExplso__FP5EXPLSP6EXPLSO",
    "UpdateShadow__FP6SHADOWf"
])


def replace_instructions_with_opcodes(asm_folder: Path) -> None:
    """Replace branch instructions with raw opcodes for functions that trigger the short loop bug."""
    nm_folder = asm_folder / "nonmatchings"
    if not nm_folder.exists():
        return

    for p in nm_folder.rglob("*.s"):
        if p.stem not in PROBLEMATIC_FUNCS:
            continue

        with p.open("r") as file:
            content = file.read()

        if re.search(OPCODE_PATTERN, content):
            content = re.sub(
                OPCODE_PATTERN,
                r"/* \1 \2\3\4\5 */  .word      0x\5\4\3\2 /* \6 */",
                content,
            )

            with p.open("w") as file:
                file.write(content)


# Generate build.ninja and objdiff.json
def generate_build(config: ProjectConfig) -> None:
    config.validate()
    objects = config.objects()

    # Run splat to generate asm and linker script
    print("Running splat to split binary...")
    import splat.scripts.split as split
    split.main([config.config_path], modes="all", verbose=False)

    # Convert GNU ld script to MWLD LCF format
    print("Converting linker script to LCF format...")
    splat_ld = config.out_path() / "SLUS_216.42.splat.ld"
    template_lcf = Path("include") / "template.lcf"
    output_lcf = config.out_path() / "SLUS_216.42.lcf"

    import subprocess
    subprocess.run([
        sys.executable,
        config.tools_dir / "convert_ld_to_lcf.py",
        "--splat-ld", str(splat_ld),
        "--template", str(template_lcf),
        "--output", str(output_lcf),
        "--build-dir", str(config.out_path()),
    ], check=True)

    # Apply short loop workaround if enabled
    if config.short_loop_workaround:
        asm_path = config.out_path() / "asm"
        if asm_path.exists():
            print("Applying short loop workaround...")
            replace_instructions_with_opcodes(asm_path)

    generate_build_ninja(config, objects)
    generate_objdiff_config(config, objects)
    # Construct a BuildConfig from objects for compile_commands generation.
    # For PS2 there are no REL modules; future Wii support can load config.json here instead.
    build_config: BuildConfig = {
        "name": config.version or "",
        "module_id": 0,
        "ldscript": "",
        "entry": "",
        "units": [{"name": name, "object": None, "autogenerated": False} for name in objects.keys()],
        "version": "1",
        "modules": [],
        "links": [],
    }
    generate_compile_commands(config, objects, build_config)


# Generate build.ninja
def generate_build_ninja(
    config: ProjectConfig,
    objects: Dict[str, Object],
) -> None:
    out = io.StringIO()
    n = ninja_syntax.Writer(out)
    n.variable("ninja_required_version", "1.3")
    n.newline()

    configure_script = Path(os.path.relpath(os.path.abspath(sys.argv[0])))
    python_lib = Path(os.path.relpath(__file__))
    python_lib_dir = python_lib.parent
    n.comment("The arguments passed to configure.py, for rerunning it.")
    n.variable("configure_args", sys.argv[1:])
    n.variable("python", f'"{sys.executable}"')
    n.newline()

    ###
    # Variables
    ###
    n.comment("Variables")
    n.variable("ldflags", make_flags_str(config.ldflags))
    if config.linker_version is None:
        sys.exit("ProjectConfig.linker_version missing")
    n.variable("mw_version", Path(config.linker_version))
    n.newline()

    ###
    # Tooling
    ###
    n.comment("Tooling")

    build_path = config.out_path()
    report_path = build_path / "report.json"
    build_tools_path = config.build_dir / "tools"
    download_tool = config.tools_dir / "download_tool.py"
    n.rule(
        name="download_tool",
        command=f"$python {download_tool} $tool $out --tag $tag",
        description="TOOL $out",
    )
    n.rule(
        name="download_tool_dir",
        command=(
            f"$python {download_tool} $tool $output_dir --tag $tag "
            "--skip-existing --stamp $out"
        ),
        description="TOOL $output_dir",
    )

    # dtk
    if config.dtk_path is not None and config.dtk_path.is_file():
        dtk = config.dtk_path
    elif config.dtk_tag:
        dtk = build_tools_path / f"dtk{EXE}"
        n.build(
            outputs=dtk,
            rule="download_tool",
            implicit=download_tool,
            variables={
                "tool": "dtk",
                "tag": config.dtk_tag,
            },
        )
    else:
        sys.exit("ProjectConfig.dtk_tag missing")

    # objdiff-cli
    if config.objdiff_path is not None and config.objdiff_path.is_file():
        objdiff = config.objdiff_path
    elif config.objdiff_tag:
        objdiff = build_tools_path / f"objdiff-cli{EXE}"
        n.build(
            outputs=objdiff,
            rule="download_tool",
            implicit=download_tool,
            variables={
                "tool": "objdiff-cli",
                "tag": config.objdiff_tag,
            },
        )
    else:
        sys.exit("ProjectConfig.objdiff_tag missing")

    if config.sjiswrap_path:
        sjiswrap = config.sjiswrap_path
    elif config.sjiswrap_tag:
        sjiswrap = build_tools_path / "sjiswrap.exe"
        n.build(
            outputs=sjiswrap,
            rule="download_tool",
            implicit=download_tool,
            variables={
                "tool": "sjiswrap",
                "tag": config.sjiswrap_tag,
            },
        )
    else:
        sys.exit("ProjectConfig.sjiswrap_tag missing")

    # wibo or wine wrapper
    wrapper = config.compiler_wrapper()
    wrapper_implicit: Optional[Path] = None
    if wrapper is not None and config.use_wibo():
        n.build(
            outputs=wrapper,
            rule="download_tool",
            implicit=download_tool,
            variables={
                "tool": "wibo",
                "tag": config.wibo_tag,
            },
        )
        wrapper_implicit = wrapper

    wrapper_cmd = f"{wrapper} " if wrapper else ""

    # Compilers
    compilers = config.compilers()
    compilers_implicit: Optional[Path] = None
    if config.compilers_path is None and config.compilers_tag is not None:
        compilers_implicit = compilers / ".downloaded"
        n.build(
            outputs=compilers_implicit,
            rule="download_tool_dir",
            implicit=download_tool,
            variables={
                "tool": "compilers",
                "tag": config.compilers_tag,
                "output_dir": compilers,
            },
        )

    # PS2 compiler (downloaded separately)
    mwccps2_implicit: Optional[Path] = None
    if config.mwccps2_tag is not None:
        mwccps2_dir = compilers / "PS2" / f"mwcps2-{config.mwccps2_tag}"
        mwccps2_implicit = mwccps2_dir / ".downloaded"
        n.build(
            outputs=mwccps2_implicit,
            rule="download_tool_dir",
            implicit=download_tool,
            variables={
                "tool": "mwccps2",
                "tag": config.mwccps2_tag,
                "output_dir": mwccps2_dir,
            },
        )
    else:
        sys.exit("ProjectConfig.mwccps2_tag missing")

    # Binutils
    binutils_implicit = None
    if config.binutils_path:
        binutils = config.binutils_path
    elif config.binutils_tag:
        binutils = config.build_dir / "binutils"
        binutils_implicit = binutils / ".downloaded"
        n.build(
            outputs=binutils_implicit,
            rule="download_tool_dir",
            implicit=download_tool,
            variables={
                "tool": "binutils",
                "tag": config.binutils_tag,
                "output_dir": binutils,
            },
        )
    else:
        sys.exit("ProjectConfig.binutils_tag missing")

    n.newline()

    ###
    # Helper rule for downloading all tools
    ###
    n.comment("Download all tools")
    n.build(
        outputs="tools",
        rule="phony",
        inputs=[wrapper, compilers_implicit, mwccps2_implicit, binutils_implicit, dtk, objdiff, sjiswrap],
    )
    n.newline()

    ###
    # Build rules
    ###
    compiler_path = compilers / "$mw_version"

    # MWCCPS2
    mwcc = compiler_path / "mwccps2.exe"
    mwcc_cmd = f"{wrapper_cmd}{mwcc} $cflags -gccdep -MMD -c $in -o $out"
    mwcc_implicit: List[Optional[Path]] = [compilers_implicit or mwcc, wrapper_implicit]

    # MWCCPS2 with UTF-8 to Shift JIS wrapper
    mwcc_sjis_cmd = f"{wrapper_cmd}{sjiswrap} {mwcc} $cflags -gccdep -MMD -c $in -o $out"
    mwcc_sjis_implicit: List[Optional[Path]] = [*mwcc_implicit, sjiswrap]

    # MWCCPS2 for precompiled headers.  With -precompile, -o names the
    # output directory and the .mch filename is supplied separately.
    mwcc_pch_cmd = (
        f"{wrapper_cmd}{mwcc} $cflags -gccdep -MMD -c $in -o $basedir "
        f"-precompile $basefilestem.mch"
    )
    mwcc_pch_implicit: List[Optional[Path]] = [*mwcc_implicit]

    mwcc_pch_sjis_cmd = (
        f"{wrapper_cmd}{sjiswrap} {mwcc} $cflags -gccdep -MMD -c $in -o $basedir "
        f"-precompile $basefilestem.mch"
    )
    mwcc_pch_sjis_implicit: List[Optional[Path]] = [*mwcc_implicit, sjiswrap]

    # Patch MWCCPS2 compiler DLLs (done after download)
    n.comment("Patch MWCCPS2 compiler DLLs")

    patch_script = config.tools_dir / "patch_compiler.py"
    n.rule(
        name="patch_compiler",
        command=f"$python {patch_script} $gc_dll_path $ps2_compiler_path $out",
        description="PATCH $ps2_compiler_path",
    )
    gc_dll_path = compilers / "GC" / "3.0a5"
    ps2_compiler_path = mwccps2_dir
    patch_marker = ps2_compiler_path / ".patched"
    n.build(
        outputs=patch_marker,
        rule="patch_compiler",
        implicit=[compilers_implicit, mwccps2_implicit, patch_script],
        variables={
            "gc_dll_path": gc_dll_path,
            "ps2_compiler_path": ps2_compiler_path,
        },
    )
    # Ensure all MWCC rules wait for compiler patching.
    mwcc_implicit.append(patch_marker)
    mwcc_sjis_implicit.append(patch_marker)
    mwcc_pch_implicit.append(patch_marker)
    mwcc_pch_sjis_implicit.append(patch_marker)
    n.newline()

    # MWLD (linker)
    mwld = compiler_path / "mwldps2.exe"
    mwld_cmd = f"{wrapper_cmd}{mwld} $ldflags -o $out $in"
    mwld_implicit: List[Optional[Path]] = [
        compilers_implicit or mwld,
        wrapper_implicit,
        patch_marker,
    ]

    # GNU as (MIPS assembler)
    gnu_as = binutils / f"mips-linux-gnu-as{EXE}"
    gnu_as_cmd = f"{gnu_as} $asflags -o $out $in"
    gnu_as_implicit = [binutils_implicit or gnu_as]

    # Transform dependency files on non-Windows
    if os.name != "nt":
        transform_dep = config.tools_dir / "transform_dep.py"
        mwcc_cmd += f" && $python {transform_dep} $basefile.d $basefile.d"
        mwcc_sjis_cmd += f" && $python {transform_dep} $basefile.d $basefile.d"
        mwcc_pch_cmd += f" && $python {transform_dep} $basefile.d $basefile.d"
        mwcc_pch_sjis_cmd += f" && $python {transform_dep} $basefile.d $basefile.d"
        mwcc_implicit.append(transform_dep)
        mwcc_sjis_implicit.append(transform_dep)
        mwcc_pch_implicit.append(transform_dep)
        mwcc_pch_sjis_implicit.append(transform_dep)

    n.comment("Link ELF file")
    n.rule(
        name="link",
        command=mwld_cmd,
        description="LINK $out",
    )
    n.newline()

    n.comment("MWCC build")
    n.rule(
        name="mwcc",
        command=mwcc_cmd,
        description="MWCC $out",
        depfile="$basefile.d",
        deps="gcc",
    )
    n.newline()

    n.comment("MWCC build (with UTF-8 to Shift JIS wrapper)")
    n.rule(
        name="mwcc_sjis",
        command=mwcc_sjis_cmd,
        description="MWCC $out",
        depfile="$basefile.d",
        deps="gcc",
    )
    n.newline()

    n.comment("Build precompiled header")
    n.rule(
        name="mwcc_pch",
        command=mwcc_pch_cmd,
        description="PCH $out",
        depfile="$basefile.d",
        deps="gcc",
    )
    n.newline()

    n.comment("Build precompiled header (with UTF-8 to Shift JIS wrapper)")
    n.rule(
        name="mwcc_pch_sjis",
        command=mwcc_pch_sjis_cmd,
        description="PCH $out",
        depfile="$basefile.d",
        deps="gcc",
    )
    n.newline()

    n.comment("Assemble asm")
    n.rule(
        name="as",
        command=gnu_as_cmd,
        description="AS $out",
    )
    n.newline()

    n.comment("Generate decomp.me context")
    decompctx = config.tools_dir / "decompctx.py"
    ctx_include_flags = " ".join(f"-I {d}" for d in config.ctx_include_dirs)
    n.rule(
        name="ctx",
        command=f"$python {decompctx} $in -o $out -d $out.d {ctx_include_flags}",
        description="CTX $in",
        depfile="$out.d",
        deps="gcc",
    )
    n.newline()

    if len(config.custom_build_rules or {}) > 0:
        n.comment("Custom project build rules (pre/post-processing)")
    for rule in config.custom_build_rules or {}:
        n.rule(
            name=cast(str, rule.get("name")),
            command=cast(str, rule.get("command")),
            description=rule.get("description", None),
            depfile=rule.get("depfile", None),
            generator=rule.get("generator", False),
            pool=rule.get("pool", None),
            restat=rule.get("restat", False),
            rspfile=rule.get("rspfile", None),
            rspfile_content=rule.get("rspfile_content", None),
            deps=rule.get("deps", None),
        )
        n.newline()

    def write_custom_step(
        step: str,
        prev_step: Optional[str] = None,
        extra_inputs: Optional[List[str]] = None,
    ) -> None:
        implicit: List[Union[str, Path]] = []
        if config.custom_build_steps and step in config.custom_build_steps:
            n.comment(f"Custom build steps ({step})")
            for custom_step in config.custom_build_steps[step]:
                outputs = cast(List[Union[str, Path]], custom_step.get("outputs"))
                if isinstance(outputs, list):
                    implicit.extend(outputs)
                else:
                    implicit.append(outputs)
                n.build(
                    outputs=outputs,
                    rule=cast(str, custom_step.get("rule")),
                    inputs=custom_step.get("inputs", None),
                    implicit=custom_step.get("implicit", None),
                    order_only=custom_step.get("order_only", None),
                    variables=custom_step.get("variables", None),
                    implicit_outputs=custom_step.get("implicit_outputs", None),
                    pool=custom_step.get("pool", None),
                    dyndep=custom_step.get("dyndep", None),
                )
                n.newline()
        n.build(
            outputs=step,
            rule="phony",
            inputs=implicit,
            order_only=prev_step,
            implicit=extra_inputs,
        )

    pch_out_names = [
        get_pch_out_name(config, pch) for pch in config.precompiled_headers or []
    ]
    write_custom_step("pre-compile", extra_inputs=pch_out_names)

    ###
    # Source files
    ###
    n.comment("Source files")
    source_inputs: List[Path] = []
    source_added: Set[Path] = set()

    if config.precompiled_headers:
        for pch in config.precompiled_headers:
            src_path_rel = Path(pch["source"])
            pch_out_abs_path = Path(get_pch_out_name(config, pch))
            cflags = list(pch["cflags"])
            if not any(flag.startswith("-lang") for flag in cflags):
                cflags.insert(0, "-lang=c++" if file_is_cpp(src_path_rel) else "-lang=c")
            shift_jis = pch.get("shift_jis", config.shift_jis)
            n.comment(f"Precompiled header {src_path_rel.with_suffix('.mch')}")
            n.build(
                outputs=pch_out_abs_path,
                rule="mwcc_pch_sjis" if shift_jis else "mwcc_pch",
                inputs=Path("include") / src_path_rel,
                variables={
                    "mw_version": Path(pch["mw_version"]),
                    "cflags": make_flags_str(cflags),
                    "basedir": os.path.dirname(pch_out_abs_path),
                    "basefile": pch_out_abs_path.with_suffix(""),
                    "basefilestem": pch_out_abs_path.stem,
                },
                implicit=mwcc_pch_sjis_implicit if shift_jis else mwcc_pch_implicit,
            )
            n.newline()

    def c_build(obj: Object, src_path: Path) -> Optional[Path]:
        if obj.src_obj_path is None or obj.src_obj_path in source_added:
            return obj.src_obj_path
        source_added.add(obj.src_obj_path)

        cflags = obj.options["cflags"]
        extra_cflags = obj.options["extra_cflags"]
        all_cflags = cflags + extra_cflags
        cflags_str = make_flags_str(all_cflags)

        lib_name = obj.options["lib"]
        build_rule = "mwcc_sjis" if obj.options["shift_jis"] else "mwcc"
        build_implicit = mwcc_sjis_implicit if obj.options["shift_jis"] else mwcc_implicit
        n.comment(f"{obj.name}: {lib_name} (linked {obj.completed})")
        n.build(
            outputs=obj.src_obj_path,
            rule=build_rule,
            inputs=src_path,
            variables={
                "mw_version": Path(obj.options["mw_version"]),
                "cflags": cflags_str,
                "basefile": obj.src_obj_path.with_suffix(""),
            },
            implicit=build_implicit,
            order_only="pre-compile",
        )
        n.newline()

        if obj.ctx_path is not None:
            n.build(
                outputs=obj.ctx_path,
                rule="ctx",
                inputs=src_path,
            )
            n.newline()

        if obj.options["add_to_all"]:
            source_inputs.append(obj.src_obj_path)

        return obj.src_obj_path

    def asm_build(obj: Object, src_path: Path, obj_path: Optional[Path]) -> Optional[Path]:
        if obj.options["asflags"] is None:
            sys.exit("ProjectConfig.asflags missing")
        asflags_str = make_flags_str(obj.options["asflags"])
        if len(obj.options["extra_asflags"]) > 0:
            extra_asflags_str = make_flags_str(obj.options["extra_asflags"])
            asflags_str += " " + extra_asflags_str

        if obj_path is None or obj_path in source_added:
            return obj_path
        source_added.add(obj_path)

        lib_name = obj.options["lib"]
        n.comment(f"{obj.name}: {lib_name} (linked {obj.completed})")
        n.build(
            outputs=obj_path,
            rule="as",
            inputs=src_path,
            variables={"asflags": asflags_str},
            implicit=gnu_as_implicit,
            order_only="pre-compile",
        )
        n.newline()

        if obj.options["add_to_all"]:
            source_inputs.append(obj_path)

        return obj_path

    # Build all objects
    link_inputs: List[Path] = []
    for obj in objects.values():
        link_built_obj = obj.completed
        built_obj_path: Optional[Path] = None

        if obj.src_path is not None and obj.src_path.exists():
            if file_is_c_cpp(obj.src_path):
                built_obj_path = c_build(obj, obj.src_path)
            elif file_is_asm(obj.src_path):
                built_obj_path = asm_build(obj, obj.src_path, obj.src_obj_path)
            else:
                sys.exit(f"Unknown source file type {obj.src_path}")
        else:
            if config.warn_missing_source or obj.completed:
                print(f"Missing source file {obj.src_path}")
            link_built_obj = False

        # Assembly overrides
        asm_obj_path: Optional[Path] = None
        if obj.asm_path is not None and obj.asm_path.exists():
            asm_obj_path = asm_build(obj, obj.asm_path, obj.asm_obj_path)
            # Only use for linking if source doesn't match
            if not link_built_obj:
                link_built_obj = True
                built_obj_path = asm_obj_path

        if link_built_obj and built_obj_path is not None:
            link_inputs.append(built_obj_path)

    n.newline()

    ###
    # Helper rule for building all source files
    ###
    n.comment("Build all source files")
    n.build(
        outputs="all_source",
        rule="phony",
        inputs=source_inputs,
    )
    n.newline()

    write_custom_step("post-compile", "pre-compile")

    ###
    # Link
    ###
    elf_path = build_path / f"{config.version}.elf"
    lcf_script = build_path / "SLUS_216.42.lcf"  # Generated LCF file

    n.comment("Link ELF")
    elf_ldflags = f"$ldflags {serialize_path(lcf_script)}"
    if config.generate_map:
        elf_map = elf_path.with_suffix(".map")
        elf_ldflags += f" -map {serialize_path(elf_map)}"
    else:
        elf_map = None

    n.build(
        outputs=elf_path,
        rule="link",
        inputs=link_inputs,
        implicit=[lcf_script, binutils, *mwld_implicit],
        implicit_outputs=elf_map,
        variables={"ldflags": elf_ldflags},
    )
    n.newline()

    write_custom_step("post-link", "post-compile")

    ###
    # Check hash
    ###
    n.comment("Check hash")
    ok_path = build_path / "ok"
    n.rule(
        name="check",
        command=f"sha1sum -c $in && touch $out",
        description="CHECK $in",
    )
    n.build(
        outputs=ok_path,
        rule="check",
        inputs=config.check_sha_path,
        implicit=[elf_path],
    )
    n.newline()

    ###
    # Calculate progress
    ###
    if config.progress:
        n.comment("Calculate progress")
        n.rule(
            name="progress",
            command=f"$python {configure_script} $configure_args progress",
            description="PROGRESS",
        )
        n.build(
            outputs="progress",
            rule="progress",
            implicit=[report_path, configure_script, python_lib],
        )

        ###
        # Generate progress report
        ###
        n.comment("Generate progress report")
        n.rule(
            name="report",
            command=f"{objdiff} report generate -o $out",
            description="REPORT",
        )
        n.build(
            outputs=report_path,
            rule="report",
            implicit=[objdiff, "objdiff.json", "all_source"],
            order_only="post-build",
        )

        n.comment("Phony edge that will always be considered dirty by ninja.")
        n.comment(
            "This can be used as an implicit to a target that should always be rerun, ignoring file modified times."
        )
        n.build(
            outputs="always",
            rule="phony",
        )
        n.newline()

        write_custom_step("post-build", "post-link")
        n.newline()

        ###
        # Regression test progress reports
        ###
        report_baseline_path = build_path / "baseline.json"
        report_changes_path = build_path / "report_changes.json"
        changes_fmt = config.tools_dir / "changes_fmt.py"
        n.comment(
            "Create a baseline progress report for later match regression testing"
        )
        n.build(
            outputs=report_baseline_path,
            rule="report",
            implicit=[objdiff, "all_source", "always"],
            order_only="post-build",
        )
        n.build(
            outputs="baseline",
            rule="phony",
            inputs=report_baseline_path,
        )
        n.comment("Check for any match regressions against the baseline")
        n.comment("Will fail if no baseline has been created")
        n.rule(
            name="report_changes",
            command=f"{objdiff} report changes --format json-pretty {report_baseline_path} $in -o $out",
            description="CHANGES",
        )
        n.build(
            outputs=report_changes_path,
            rule="report_changes",
            inputs=report_path,
            implicit=[objdiff, "always"],
        )
        n.rule(
            name="changes_fmt",
            command=f"$python {changes_fmt} $args $in",
            description="CHANGESFMT",
        )
        n.build(
            outputs="changes",
            rule="changes_fmt",
            inputs=report_changes_path,
            implicit=changes_fmt,
        )
        n.build(
            outputs="changes_all",
            rule="changes_fmt",
            inputs=report_changes_path,
            implicit=changes_fmt,
            variables={"args": "--all"},
        )

    ###
    # Regenerate on change
    ###
    n.comment("Reconfigure on change")
    n.rule(
        name="configure",
        command=f"$python {configure_script} $configure_args",
        generator=True,
        description=f"RUN {configure_script}",
    )
    n.build(
        outputs=["build.ninja", "objdiff.json"],
        rule="configure",
        implicit=[
            configure_script,
            python_lib,
            python_lib_dir / "ninja_syntax.py",
            config.config_path,
            *(config.reconfig_deps or []),
        ],
    )
    n.newline()

    ###
    # Default rule
    ###
    n.comment("Default rule")
    if config.non_matching:
        n.default(elf_path)
    elif config.progress:
        n.default("progress")
    else:
        n.default(ok_path)

    # Write build.ninja
    with open("build.ninja", "w", encoding="utf-8") as f:
        f.write(out.getvalue())
    out.close()


# Generate objdiff.json
def generate_objdiff_config(
    config: ProjectConfig,
    objects: Dict[str, Object],
) -> None:
    # Load existing objdiff.json
    existing_units: Dict[str, Any] = {}
    if Path("objdiff.json").is_file():
        with open("objdiff.json", "r", encoding="utf-8") as r:
            existing_config = json.load(r)
            existing_units = {
                unit["name"]: unit for unit in existing_config.get("units", [])
            }

    if config.ninja_path:
        ninja = str(config.ninja_path.absolute())
    else:
        ninja = "ninja"

    objdiff_config: Dict[str, Any] = {
        "$schema": "https://raw.githubusercontent.com/encounter/objdiff/main/config.schema.json",
        "min_version": "2.0.0-beta.5",
        "custom_make": ninja,
        "build_target": False,
        "watch_patterns": [
            "*.c",
            "*.cc",
            "*.cp",
            "*.cpp",
            "*.cxx",
            "*.c++",
            "*.h",
            "*.hh",
            "*.hp",
            "*.hpp",
            "*.hxx",
            "*.h++",
            "*.pch",
            "*.pch++",
            "*.inc",
            "*.py",
            "*.yml",
            "*.txt",
            "*.json",
        ],
        "units": [],
        "progress_categories": [],
    }

    # decomp.me compiler name mapping for PS2
    PS2_COMPILER_MAP = {
        "PS2/mwcps2-3.0.1b198-051011": "mwcps2-3.0.1b198-051011",
    }

    for obj in objects.values():
        unit_config: Dict[str, Any] = {
            "name": obj.name,
            "target_path": obj.asm_obj_path,
            "base_path": None,
            "scratch": None,
            "metadata": {
                "complete": None,
                "reverse_fn_order": None,
                "source_path": None,
                "progress_categories": (
                    [obj.options["progress_category"]]
                    if obj.options["progress_category"]
                    else []
                ),
                "auto_generated": False,
            },
            "symbol_mappings": None,
        }

        # Preserve existing symbol mappings
        existing_unit = existing_units.get(obj.name)
        if existing_unit is not None:
            unit_config["symbol_mappings"] = existing_unit.get("symbol_mappings")

        src_exists = obj.src_path is not None and obj.src_path.exists()
        if src_exists:
            unit_config["base_path"] = obj.src_obj_path
            unit_config["metadata"]["source_path"] = obj.src_path

        # Only generate scratch block for C/C++ source files
        if obj.src_path is not None and file_is_c_cpp(obj.src_path):
            def keep_flag(flag: str) -> bool:
                return not any(
                    flag.startswith(prefix)
                    for prefix in ("-i ", "-i-", "-I ", "-I+", "-I-")
                )

            all_cflags = list(
                filter(
                    keep_flag,
                    (obj.options["cflags"] or []) + (obj.options["extra_cflags"] or []),
                )
            )

            # Check for reverse_fn_order (-inline deferred)
            reverse_fn_order = False
            for flag in all_cflags:
                if not flag.startswith("-inline "):
                    continue
                for value in flag.split(" ")[1].split(","):
                    if value == "deferred":
                        reverse_fn_order = True
                    elif value == "nodeferred":
                        reverse_fn_order = False

            compiler_version = PS2_COMPILER_MAP.get(obj.options["mw_version"])
            if compiler_version is None:
                print(
                    f"Missing scratch compiler mapping for {obj.options['mw_version']}"
                )
            else:
                cflags_str = make_flags_str(all_cflags)
                preset_id = obj.options["scratch_preset_id"] or config.scratch_preset_id
                unit_config["scratch"] = {
                    "platform": config.scratch_platform,
                    "compiler": compiler_version,
                    "c_flags": cflags_str,
                    "preset_id": preset_id,
                }
                if src_exists:
                    unit_config["scratch"].update(
                        {
                            "ctx_path": obj.ctx_path,
                            "build_ctx": True,
                        }
                    )

            unit_config["metadata"].update(
                {
                    "complete": obj.completed if src_exists else None,
                    "reverse_fn_order": reverse_fn_order,
                }
            )

        objdiff_config["units"].append(unit_config)

    # Add progress categories
    for category in config.progress_categories:
        objdiff_config["progress_categories"].append(
            {
                "id": category.id,
                "name": category.name,
            }
        )

    def cleandict(d: Any) -> Any:
        if isinstance(d, dict):
            return {k: cleandict(v) for k, v in d.items() if v is not None}
        elif isinstance(d, list):
            return [cleandict(v) for v in d]
        return d

    def unix_path(input: Any) -> str:
        return str(input).replace(os.sep, "/") if input else ""

    with open("objdiff.json", "w", encoding="utf-8") as w:
        json.dump(cleandict(objdiff_config), w, indent=2, default=unix_path)


# Generate compile_commands.json for clangd
def generate_compile_commands(
    config: ProjectConfig,
    objects: Dict[str, Object],
    build_config: Optional[BuildConfig],
) -> None:
    if build_config is None or not config.generate_compile_commands:
        return

    # The following code attempts to convert mwcc flags to clang flags
    # for use with clangd.

    # Flags to ignore explicitly
    CFLAG_IGNORE: Set[str] = {
        # Search order modifier
        # Has a different meaning to Clang, and would otherwise
        # be picked up by the include passthrough prefix
        "-I-",
        "-i-",
    }
    CFLAG_IGNORE_PREFIX: Tuple[str, ...] = (
        # Recursive includes are not supported by modern compilers
        "-ir ",
    )

    # Flags to replace
    CFLAG_REPLACE: Dict[str, str] = {}
    CFLAG_REPLACE_PREFIX: Tuple[Tuple[str, str], ...] = (
        # Includes
        # MWCC uses "-i path" or "-I path" (with space) for includes
        ("-i ", "-I"),
        ("-I ", "-I"),
        ("-I+", "-I"),
        # Defines
        ("-d ", "-D"),
        ("-D ", "-D"),
        ("-D+", "-D"),
    )

    # Flags with a finite set of options
    CFLAG_REPLACE_OPTIONS: Tuple[Tuple[str, Dict[str, Tuple[str, ...]]], ...] = (
        # Exceptions
        (
            "-Cpp_exceptions",
            {
                "off": ("-fno-cxx-exceptions",),
                "on": ("-fcxx-exceptions",),
            },
        ),
        # RTTI
        (
            "-RTTI",
            {
                "off": ("-fno-rtti",),
                "on": ("-frtti",),
            },
        ),
        # Language configuration
        (
            "-lang",
            {
                "c": ("--language=c", "--std=c99"),
                "c99": ("--language=c", "--std=c99"),
                "c++": ("--language=c++", "--std=c++98"),
                "cplus": ("--language=c++", "--std=c++98"),
            },
        ),
        # Enum size
        (
            "-enum",
            {
                "min": ("-fshort-enums",),
                "int": ("-fno-short-enums",),
            },
        ),
        # Common BSS
        (
            "-common",
            {
                "off": ("-fno-common",),
                "on": ("-fcommon",),
            },
        ),
    )

    # Flags to pass through
    CFLAG_PASSTHROUGH: Set[str] = set()
    CFLAG_PASSTHROUGH_PREFIX: Tuple[str, ...] = (
        "-I",  # includes
        "-D",  # defines
    )

    clangd_config = []

    def add_unit(build_obj: BuildConfigUnit) -> None:
        obj = objects.get(build_obj["name"])
        if obj is None:
            return

        # Skip unresolved objects
        if (
            obj.src_path is None
            or obj.src_obj_path is None
            or not file_is_c_cpp(obj.src_path)
        ):
            return

        # Gather cflags for source file
        cflags: list[str] = []

        def append_cflags(flags: Iterable[str]) -> None:
            if not flags:
                return

            # Match a flag against either a set of concrete flags, or a set of prefixes.
            def flag_match(
                flag: str, concrete: Set[str], prefixes: Tuple[str, ...]
            ) -> bool:
                if flag in concrete:
                    return True

                for prefix in prefixes:
                    if flag.startswith(prefix):
                        return True

                return False

            # Determine whether a flag should be ignored.
            def should_ignore(flag: str) -> bool:
                return flag_match(flag, CFLAG_IGNORE, CFLAG_IGNORE_PREFIX)

            # Determine whether a flag should be passed through.
            def should_passthrough(flag: str) -> bool:
                return flag_match(flag, CFLAG_PASSTHROUGH, CFLAG_PASSTHROUGH_PREFIX)

            # Attempts replacement for the given flag.
            def try_replace(flag: str) -> bool:
                replacement = CFLAG_REPLACE.get(flag)
                if replacement is not None:
                    cflags.append(replacement)
                    return True

                for prefix, replacement in CFLAG_REPLACE_PREFIX:
                    if flag.startswith(prefix):
                        cflags.append(flag.replace(prefix, replacement, 1))
                        return True

                for prefix, options in CFLAG_REPLACE_OPTIONS:
                    if not flag.startswith(prefix):
                        continue

                    # "-lang c99" and "-lang=c99" are both generally valid option forms
                    option = flag.removeprefix(prefix).removeprefix("=").lstrip()
                    replacements = options.get(option)
                    if replacements is not None:
                        cflags.extend(replacements)

                    return True

                return False

            for flag in flags:
                # Ignore flags first
                if should_ignore(flag):
                    continue

                # Then find replacements
                if try_replace(flag):
                    continue

                # Pass flags through last
                if should_passthrough(flag):
                    cflags.append(flag)
                    continue

        append_cflags(obj.options["cflags"])
        append_cflags(obj.options["extra_cflags"])
        cflags.extend(config.extra_clang_flags)
        cflags.extend(obj.options["extra_clang_flags"])

        unit_config = {
            "directory": Path.cwd(),
            "file": obj.src_path,
            "output": obj.src_obj_path,
            "arguments": [
                "clang",
                "-nostdinc",
                "-fno-builtin",
                "--target=mipsel-none-elf",
                *cflags,
                "-c",
                obj.src_path,
                "-o",
                obj.src_obj_path,
            ],
        }
        clangd_config.append(unit_config)

    # Add DOL units
    for unit in build_config["units"]:
        add_unit(unit)

    # Add REL units
    for module in build_config["modules"]:
        for unit in module["units"]:
            add_unit(unit)

    # Write compile_commands.json
    with open("compile_commands.json", "w", encoding="utf-8") as w:

        def default_format(o):
            if isinstance(o, Path):
                return o.resolve().as_posix()
            return str(o)

        json.dump(clangd_config, w, indent=2, default=default_format)


# Print progress information
def calculate_progress(config: ProjectConfig) -> None:
    config.validate()
    out_path = config.out_path()
    report_path = out_path / "report.json"
    if not report_path.is_file():
        sys.exit(f"Report file {report_path} does not exist")

    with open(report_path, "r", encoding="utf-8") as f:
        report_data = json.load(f)

    # Convert string numbers to int
    def convert_numbers(data: Dict[str, Any]) -> None:
        for key, value in data.items():
            if isinstance(value, str) and value.isdigit():
                data[key] = int(value)

    convert_numbers(report_data["measures"])
    for category in report_data.get("categories", []):
        convert_numbers(category["measures"])

    # Print progress
    print("Progress:")

    def print_category(name: str, measures: Dict[str, Any]) -> None:
        total_code = measures.get("total_code", 0)
        matched_code = measures.get("matched_code", 0)
        matched_code_percent = measures.get("matched_code_percent", 0)
        total_data = measures.get("total_data", 0)
        matched_data = measures.get("matched_data", 0)
        matched_data_percent = measures.get("matched_data_percent", 0)
        total_functions = measures.get("total_functions", 0)
        matched_functions = measures.get("matched_functions", 0)
        complete_code_percent = measures.get("complete_code_percent", 0)
        total_units = measures.get("total_units", 0)
        complete_units = measures.get("complete_units", 0)

        print(f"  {name}: {matched_code_percent:.2f}% matched, {complete_code_percent:.2f}% linked ({complete_units} / {total_units} files)")
        print(f"    Code: {matched_code} / {total_code} bytes ({matched_functions} / {total_functions} functions)")
        print(f"    Data: {matched_data} / {total_data} bytes ({matched_data_percent:.2f}%)")

    print_category("All", report_data["measures"])
    for category in report_data.get("categories", []):
        print_category(category["name"], category["measures"])
